portfolio/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls'))
]

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    # points to site/projects
    path('', views.all_projects, name='all_projects'), 
    # '<int:pk>' gets an integer representing the primary key for 
    # an object in the database (only an int is accepted)
    # the first param is passed to the second param, basically
    path('<int:pk>', views.project_detail, name='project_detail'),
]

projects/models.py
from django.db import models


'''
model for the database
will contain 5 columns
id, title, description, technology, image
id is an incrementing integer, added automatically by django
'''
class Project(models.Model):
    title = models.CharField(max_length=100)
    technology = models.CharField(max_length=20)
    summary = models.CharField(max_length=100, default='')
    description = models.TextField()
    image = models.CharField(max_length=100)

projects/views.py
'''
Each function here represents a view.
This is where the logic is set out for actions
such as retrieving data from the database.
'''

from django.shortcuts import render
from projects.models import Project


def all_projects(request):
    '''
    Function to return all projects in the database.
    '''
    # query database to return all project objects stored therein
    projects = Project.objects.all()
    # param 1 = request
    # param 2 = the template to be used
    # param 3 = all projects object as a dict
    return render(request, 'projects/all_projects.html', {'projects': projects})


def project_detail(request, pk):
    '''
    Function to return the details of a single project.
    '''
    # retrieve the object having the primary key in question
    project = Project.objects.get(pk=pk)
    # param 1 = request
    # param 2 = the template to be used
    # param 3 = the individual project in question
    return render(request, 'projects/detail.html', {'project': project})

projects/templates/projects/all_projects.html
{% extends 'projects/base.html' %}
{% load static %}

{% block content %}

    <div class="container mb-10">
        <div class="row">

        {% for project in projects %}

            <div class="col-md-4">
                <div class="card mb-4">

                    <div class="card-header text-center">
                        <h5>{{ project.title }}</h5>
                    </div>

                    <img class="img-fluid mx-auto mt-4 mb-2" src="{% static project.image %}" alt="{{ project.description }}" width="120" height="120">

                    <div class="card-body">
                        <p class="card-text">{{ project.summary }}</p>
                        <a class="btn btn-outline-primary" href="{% url 'projects:project_detail' project.pk %}">Read more</a>
                    </div>

                </div>
            </div>

        {% endfor %}

        </div>
    </div>

{% endblock %}

projects/templates/projects/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Portfolio</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="../../static/projects/css/custom.css">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>

        <div class="container" id="page-container">

            <div class="row">

                <!-- Top banner -->
                <div class="col-12 bg-light py-5" >
                    <h2 class="text-center text-dark">Basic Portfolio</h2>
                </div>

                <!-- Main body -->
                {% block content %}
                {% endblock %}
            </div>

            <footer class="footer"">
                <div class="container">
                    <span class="text-dark">Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a></span>
                </div>
            </footer>

        </div>

    </body>
</html>

projects/templates/projects/detail.html
{% extends 'projects/base.html' %}
{% load static %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-1"></div>

            <!-- Image -->
            <div class="col-md-2 text-center pt-4">
                <img class="img-fluid" src="{% static project.image %}" alt="{{ project.description }}" width="120" height="120">
            </div>

            <!-- Text -->
            <div class="col-md-8 pt-2">
                <h4 class="pb-3">{{ project.title }}</h4>
                <h5>About the project</h5>
                <p>{{ project.description|linebreaksbr }}</p>
                <h5 class="pt-2">Built with:</h5>
                <p>{{ project.technology }}</p>
            </div>

        </div>
    </div>

{% endblock %}